- AAs:
    - aa_ability: schema/categories/aas/aa_ability.md
    - aa_ranks: schema/categories/aas/aa_ranks.md
    - aa_rank_effects: schema/categories/aas/aa_rank_effects.md
    - aa_rank_prereqs: schema/categories/aas/aa_rank_prereqs.md
- Account:
    - account: schema/categories/account/account.md
    - account_flags: schema/categories/account/account_flags.md
    - account_ip: schema/categories/account/account_ip.md
    - account_rewards: schema/categories/account/account_rewards.md
    - sharedbank: schema/categories/account/sharedbank.md
- Admin:
    - banned_ips: schema/categories/admin/banned_ips.md
    - bot_command_settings: schema/categories/admin/bot_command_settings.md
    - bug_reports: schema/categories/admin/bug_reports.md
    - bugs: schema/categories/admin/bugs.md
    - chatchannels: schema/categories/admin/chatchannels.md
    - command_settings: schema/categories/admin/command_settings.md
    - db_version: schema/categories/admin/db_version.md
    - discovered_items: schema/categories/admin/discovered_items.md
    - eqtime: schema/categories/admin/eqtime.md
    - eventlog: schema/categories/admin/eventlog.md
    - gm_ips: schema/categories/admin/gm_ips.md
    - hackers: schema/categories/admin/hackers.md
    - ip_exemptions: schema/categories/admin/ip_exemptions.md
    - level_exp_mods: schema/categories/admin/level_exp_mods.md
    - logsys_categories: schema/categories/admin/logsys_categories.md
    - name_filter: schema/categories/admin/name_filter.md
    - perl_event_export_settings: schema/categories/admin/perl_event_export_settings.md
    - petitions: schema/categories/admin/petitions.md
    - profanity_list: schema/categories/admin/profanity_list.md
    - reports: schema/categories/admin/reports.md
    - saylink: schema/categories/admin/saylink.md
    - start_zones: schema/categories/admin/start_zones.md
    - starting_items: schema/categories/admin/starting_items.md
    - variables: schema/categories/admin/variables.md
    - veteran_reward_templates: schema/categories/admin/veteran_reward_templates.md
- Adventures:
    - adventure_details: schema/categories/adventures/adventure_details.md
    - adventure_members: schema/categories/adventures/adventure_members.md
    - adventure_stats: schema/categories/adventures/adventure_stats.md
    - adventure_template: schema/categories/adventures/adventure_template.md
    - adventure_template_entry: schema/categories/adventures/adventure_template_entry.md
    - adventure_template_entry_flavor: schema/categories/adventures/adventure_template_entry_flavor.md
- Alternate Currency:
    - alternate_currency: schema/categories/alternate-currency/alternate_currency.md
- Books:
    - books: schema/categories/books/books.md
- Bots:
    - bot_buffs: schema/categories/bots/bot_buffs.md
    - bot_data: schema/categories/bots/bot_data.md
    - bot_groups: schema/categories/bots/bot_groups.md
    - bot_group_members: schema/categories/bots/bot_group_members.md
    - bot_guild_members: schema/categories/bots/bot_guild_members.md
    - bot_heal_rotations: schema/categories/bots/bot_heal_rotations.md
    - bot_heal_rotation_members: schema/categories/bots/bot_heal_rotation_members.md
    - bot_heal_rotation_targets: schema/categories/bots/bot_heal_rotation_targets.md
    - bot_inspect_messages: schema/categories/bots/bot_inspect_messages.md
    - bot_inventories: schema/categories/bots/bot_inventories.md
    - bot_owner_options: schema/categories/bots/bot_owner_options.md
    - bot_pets: schema/categories/bots/bot_pets.md
    - bot_pet_buffs: schema/categories/bots/bot_pet_buffs.md
    - bot_pet_inventories: schema/categories/bots/bot_pet_inventories.md
    - bot_spells_entries: schema/categories/bots/bot_spells_entries.md
    - bot_spell_casting_chances: schema/categories/bots/bot_spell_casting_chances.md
    - bot_stances: schema/categories/bots/bot_stances.md
    - bot_timers: schema/categories/bots/bot_timers.md
- Buyers:
    - buyer: schema/categories/buyers/buyer.md
- Characters:
    - character_activities: schema/categories/characters/character_activities.md
    - character_alternate_abilities: schema/categories/characters/character_alternate_abilities.md
    - character_alt_currency: schema/categories/characters/character_alt_currency.md
    - character_auras: schema/categories/characters/character_auras.md
    - character_bandolier: schema/categories/characters/character_bandolier.md
    - character_bind: schema/categories/characters/character_bind.md
    - character_buffs: schema/categories/characters/character_buffs.md
    - character_corpses: schema/categories/characters/character_corpses.md
    - character_corpse_items: schema/categories/characters/character_corpse_items.md
    - character_currency: schema/categories/characters/character_currency.md
    - character_data: schema/categories/characters/character_data.md
    - character_disciplines: schema/categories/characters/character_disciplines.md
    - character_enabledtasks: schema/categories/characters/character_enabledtasks.md
    - character_expedition_lockouts: schema/categories/characters/character_expedition_lockouts.md
    - character_inspect_messages: schema/categories/characters/character_inspect_messages.md
    - character_item_recast: schema/categories/characters/character_item_recast.md
    - character_languages: schema/categories/characters/character_languages.md
    - character_leadership_abilities: schema/categories/characters/character_leadership_abilities.md
    - character_material: schema/categories/characters/character_material.md
    - character_memmed_spells: schema/categories/characters/character_memmed_spells.md
    - character_pet_buffs: schema/categories/characters/character_pet_buffs.md
    - character_pet_info: schema/categories/characters/character_pet_info.md
    - character_pet_inventory: schema/categories/characters/character_pet_inventory.md
    - character_potionbelt: schema/categories/characters/character_potionbelt.md
    - character_skills: schema/categories/characters/character_skills.md
    - character_spells: schema/categories/characters/character_spells.md
    - character_tasks: schema/categories/characters/character_tasks.md
    - character_task_lockouts: schema/categories/characters/character_task_lockouts.md
    - character_tribute: schema/categories/characters/character_tribute.md
    - char_create_combinations: schema/categories/characters/char_create_combinations.md
    - char_create_point_allocations: schema/categories/characters/char_create_point_allocations.md
    - char_recipe_list: schema/categories/characters/char_recipe_list.md
    - friends: schema/categories/characters/friends.md
    - keyring: schema/categories/characters/keyring.md
    - lfguild: schema/categories/characters/lfguild.md
    - mail: schema/categories/characters/mail.md
    - player_titlesets: schema/categories/characters/player_titlesets.md
- Client Files:
    - base_data: schema/categories/client-files/base_data.md
    - db_str: schema/categories/client-files/db_str.md
    - skill_caps: schema/categories/client-files/skill_caps.md
- Data Storage:
    - data_buckets: schema/categories/data-storage/data_buckets.md
    - quest_globals: schema/categories/data-storage/quest_globals.md
- Doors:
    - doors: schema/categories/doors/doors.md
- Expeditions:
    - character_expedition_lockouts: schema/categories/expeditions/character_expedition_lockouts.md
    - expeditions: schema/categories/expeditions/expeditions.md
    - expedition_lockouts: schema/categories/expeditions/expedition_lockouts.md
- Factions:
    - faction_base_data: schema/categories/factions/faction_base_data.md
    - faction_list: schema/categories/factions/faction_list.md
    - faction_list_prefix: schema/categories/factions/faction_list_prefix.md
    - faction_values: schema/categories/factions/faction_values.md
- Graveyards:
    - graveyard: schema/categories/graveyards/graveyard.md
- Ground Spawns:
    - ground_spawns: schema/categories/ground-spawns/ground_spawns.md
- Groups:
    - group_id: schema/categories/groups/group_id.md
    - group_leaders: schema/categories/groups/group_leaders.md
- Guilds:
    - guilds: schema/categories/guilds/guilds.md
    - guild_bank: schema/categories/guilds/guild_bank.md
    - guild_ranks: schema/categories/guilds/guild_ranks.md
    - guild_members: schema/categories/guilds/guild_members.md
    - guild_relations: schema/categories/guilds/guild_relations.md
- Grids:
    - grid: schema/categories/grids/grid.md
    - grid_entries: schema/categories/grids/grid_entries.md
- Horses:
    - horses: schema/categories/horses/horses.md
- Instances:
    - instance_list: schema/categories/instances/instance_list.md
    - instance_list_player: schema/categories/instances/instance_list_player.md
- Inventory:
    - inventory: schema/categories/inventory/inventory.md
    - inventory_snapshots: schema/categories/inventory/inventory_snapshots.md
    - inventory_versions: schema/categories/inventory/inventory_versions.md
- Items:
    - items: schema/categories/items/items.md
    - item_tick: schema/categories/items/item_tick.md
- Loginserver:
    - login_accounts: schema/categories/loginserver/login_accounts.md
    - login_api_tokens: schema/categories/loginserver/login_api_tokens.md
    - login_server_admins: schema/categories/loginserver/login_server_admins.md
    - login_server_list_types: schema/categories/loginserver/login_server_list_types.md
    - login_world_servers: schema/categories/loginserver/login_world_servers.md
- Loot:
    - global_loot: schema/categories/loot/global_loot.md
    - lootdrop: schema/categories/loot/lootdrop.md
    - lootdrop_entries: schema/categories/loot/lootdrop_entries.md
    - loottable: schema/categories/loot/loottable.md
    - loottable_entries: schema/categories/loot/loottable_entries.md
- Mercenaries:
    - mercs: schema/categories/mercenaries/mercs.md
    - merc_armorinfo: schema/categories/mercenaries/merc_armorinfo.md
    - merc_buffs: schema/categories/mercenaries/merc_buffs.md
    - merc_inventory: schema/categories/mercenaries/merc_inventory.md
    - merc_merchant_entries: schema/categories/mercenaries/merc_merchant_entries.md
    - merc_merchant_templates: schema/categories/mercenaries/merc_merchant_templates.md
    - merc_merchant_template_entries: schema/categories/mercenaries/merc_merchant_template_entries.md
    - merc_name_types: schema/categories/mercenaries/merc_name_types.md
    - merc_npc_types: schema/categories/mercenaries/merc_npc_types.md
    - merc_spell_lists: schema/categories/mercenaries/merc_spell_lists.md
    - merc_spell_list_entries: schema/categories/mercenaries/merc_spell_list_entries.md
    - merc_stance_entries: schema/categories/mercenaries/merc_stance_entries.md
    - merc_stats: schema/categories/mercenaries/merc_stats.md
    - merc_subtypes: schema/categories/mercenaries/merc_subtypes.md
    - merc_templates: schema/categories/mercenaries/merc_templates.md
    - merc_types: schema/categories/mercenaries/merc_types.md
    - merc_weaponinfo: schema/categories/mercenaries/merc_weaponinfo.md
- Merchants:
    - merchantlist: schema/categories/merchants/merchantlist.md
    - merchantlist_temp: schema/categories/merchants/merchantlist_temp.md
- NPCs:
    - npc_emotes: schema/categories/npcs/npc_emotes.md
    - npc_faction: schema/categories/npcs/npc_faction.md
    - npc_faction_entries: schema/categories/npcs/npc_faction_entries.md
    - npc_scale_global_base: schema/categories/npcs/npc_scale_global_base.md
    - npc_spells: schema/categories/npcs/npc_spells.md
    - npc_spells_effects: schema/categories/npcs/npc_spells_effects.md
    - npc_spells_effects_entries: schema/categories/npcs/npc_spells_effects_entries.md
    - npc_spells_entries: schema/categories/npcs/npc_spells_entries.md
    - npc_types: schema/categories/npcs/npc_types.md
    - npc_types_tint: schema/categories/npcs/npc_types_tint.md
    - proximities: schema/categories/npcs/proximities.md
- Objects:
    - object: schema/categories/objects/object.md
    - object_contents: schema/categories/objects/object_contents.md
- Pets:
    - pets: schema/categories/pets/pets.md
    - pets_equipmentset: schema/categories/pets/pets_equipmentset.md
    - pets_equipmentset_entries: schema/categories/pets/pets_equipmentset_entries.md
- Query Server:
    - qs_merchant_transaction_record: schema/categories/query-server/qs_merchant_transaction_record.md
    - qs_merchant_transaction_record_entries: schema/categories/query-server/qs_merchant_transaction_record_entries.md
    - qs_player_aa_rate_hourly: schema/categories/query-server/qs_player_aa_rate_hourly.md
    - qs_player_delete_record: schema/categories/query-server/qs_player_delete_record.md
    - qs_player_delete_record_entries: schema/categories/query-server/qs_player_delete_record_entries.md
    - qs_player_events: schema/categories/query-server/qs_player_events.md
    - qs_player_handin_record: schema/categories/query-server/qs_player_handin_record.md
    - qs_player_handin_record_entries: schema/categories/query-server/qs_player_handin_record_entries.md
    - qs_player_move_record: schema/categories/query-server/qs_player_move_record.md
    - qs_player_move_record_entries: schema/categories/query-server/qs_player_move_record_entries.md
    - qs_player_npc_kill_record: schema/categories/query-server/qs_player_npc_kill_record.md
    - qs_player_npc_kill_record_entries: schema/categories/query-server/qs_player_npc_kill_record_entries.md
    - qs_player_speech: schema/categories/query-server/qs_player_speech.md
    - qs_player_trade_record: schema/categories/query-server/qs_player_trade_record.md
    - qs_player_trade_record_entries: schema/categories/query-server/qs_player_trade_record_entries.md
- Scheduler:
    - server_scheduled_events: schema/categories/scheduler/server_scheduled_events.md
- Raids:
    - raid_details: schema/categories/raids/raid_details.md
    - raid_leaders: schema/categories/raids/raid_leaders.md
    - raid_members: schema/categories/raids/raid_members.md
- Rules:
    - rule_sets: schema/categories/rules/rule_sets.md
    - rule_values: schema/categories/rules/rule_values.md
- Spawns:
    - respawn_times: schema/categories/spawns/respawn_times.md
    - spawn2: schema/categories/spawns/spawn2.md
    - spawnentry: schema/categories/spawns/spawnentry.md
    - spawngroup: schema/categories/spawns/spawngroup.md
    - spawn_conditions: schema/categories/spawns/spawn_conditions.md
    - spawn_condition_values: schema/categories/spawns/spawn_condition_values.md
    - spawn_events: schema/categories/spawns/spawn_events.md
- Spells:
    - auras: schema/categories/spells/auras.md
    - blocked_spells: schema/categories/spells/blocked_spells.md
    - damageshieldtypes: schema/categories/spells/damageshieldtypes.md
    - spell_buckets: schema/categories/spells/spell_buckets.md
    - spell_globals: schema/categories/spells/spell_globals.md
    - spells_new: schema/categories/spells/spells_new.md
- Tasks:
    - completed_tasks: schema/categories/tasks/completed_tasks.md
    - goallists: schema/categories/tasks/goallists.md
    - shared_task_activities: schema/categories/tasks/shared_task_activities.md
    - shared_task_members: schema/categories/tasks/shared_task_members.md
    - shared_task_state: schema/categories/tasks/shared_task_state.md
    - task_activities: schema/categories/tasks/task_activities.md
    - task_replay_groups: schema/categories/tasks/task_replay_groups.md
    - tasks: schema/categories/tasks/tasks.md
    - tasksets: schema/categories/tasks/tasksets.md
- Timers:
    - timers: schema/categories/timers/timers.md
- Titles:
    - titles: schema/categories/titles/titles.md
- Trader:
    - trader: schema/categories/trader/trader.md
    - trader_audit: schema/categories/trader/trader_audit.md
- Tradeskills:
    - fishing: schema/categories/tradeskills/fishing.md
    - forage: schema/categories/tradeskills/forage.md
    - tradeskill_recipe: schema/categories/tradeskills/tradeskill_recipe.md
    - tradeskill_recipe_entries: schema/categories/tradeskills/tradeskill_recipe_entries.md
- Traps:
    - ldon_trap_entries: schema/categories/traps/ldon_trap_entries.md
    - ldon_trap_templates: schema/categories/traps/ldon_trap_templates.md
    - traps: schema/categories/traps/traps.md
- Tributes:
    - tributes: schema/categories/tributes/tributes.md
    - tribute_levels: schema/categories/tributes/tribute_levels.md
- Zone:
    - launcher: schema/categories/zone/launcher.md
    - launcher_zones: schema/categories/zone/launcher_zones.md
    - zone: schema/categories/zone/zone.md
    - zone_flags: schema/categories/zone/zone_flags.md
    - zone_points: schema/categories/zone/zone_points.md
